### PR TITLE
Add Common Lisp implementation

### PR DESCRIPTION
**Pull request by uninhm**
TO-DO:
- [x] Try some others of the incredibly vast amount of Common Lisp implementations (for instance, SBCL is one of the most well-known).

### CODE REVIEW

**Comment by uninhm** [comment]
To my own surprise, SBCL is incredibly fast! And type declarations did a speed up of a... 97%!!!!

**Comment by uninhm** [comment]
[#9593a2f](https://github.com/jabbalaci/SpeedTests/pull/34/commits/9593a2fdb86115b11a732c06e4f96676d26b9730) did around a 13% improvement for me.

**Comment by jabbalaci** [comment]
clisp is terribly slow. Why is that? On my machine it runs for 1 hour 51 minutes. It's a negative record.

**Comment by uninhm** [comment]
@jabbalaci Maybe try doing
`$ clisp -C main.cl`
That should be faster

**Comment by jabbalaci** [comment]
What does it do? The help says:

     -C            - set *LOAD-COMPILING* to T

What does it mean?

If you compile to byte-code with `-c`, does it help?

**Comment by uninhm** [comment]
@jabbalaci AFAIK `-C` is the same as doing `-c` and then running

**Comment by jabbalaci** [comment]
Thanks! It was integrated, see the README.

**Pull request merged**
