### PR TITLE
[Mojo] Use `InlineArray` for `cache` to match C

### PR DESCRIPTION
**Pull request by soraros**
I think it's a good example of progressive disclosure of complexity.

- Make type (defaults to `UInt32`) an alias
- Use `InlineArray` instead of `List` for cache, remove bound check
- Format code using `mblack` (official Mojo code formatter with default settings)

### CODE REVIEW

**Comment by Yona5** [comment]
Running this version of code on the mojo playground is slower than main_v2.mojo.

**Comment by dorjeduck** [comment]
On my Mac 2 Pro laptop, i get nearly identical performance results:

List / Uint32 version:
```
Benchmark 1: ./main2
  Time (mean ± σ):      1.623 s ±  0.001 s    [User: 1.603 s, System: 0.020 s]
  Range (min … max):    1.622 s …  1.624 s    2 runs
 ```
 
 InlineArray / Uint32 version (this PR)
 ```
Benchmark 1: ./main4
  Time (mean ± σ):      1.678 s ±  0.016 s    [User: 1.652 s, System: 0.021 s]
  Range (min … max):    1.666 s …  1.689 s    2 runs
 ```
 Would love to see benchmark results of these two on other devices.

**Comment by soraros** [comment]
I'm not that concerned with performance (I know they should be roughly identical, for the generated assembly says so). This PR is more to showcase how to write such a program using arrays.

BTW, try running this [benchmark script](https://github.com/jabbalaci/SpeedTests/pull/63#issuecomment-2426750244).

**Comment by dorjeduck** [comment]
Thanks for the script: I get 

--------------------------------------------------------------------------------
Benchmark results
--------------------------------------------------------------------------------
name,met (ms),iters
"list",2486.6900000000001,3
"array",1636.8683333333331,3

;-)

**Comment by martinvuyk** [comment]
see my [comment about the benchmark](https://github.com/jabbalaci/SpeedTests/pull/63#issuecomment-2427057749), it is not so straightforward a change

**Comment by jabbalaci** [comment]
Why is it necessary to modify v1?

**Comment by soraros** [comment]
@jabbalaci Just that I wanted to minimise unrelated differences (they are now more or less in a "canonical form"). If you don't like the cosmetic changes to v1 I can revert.

**Comment by jabbalaci** [comment]
A `@parameter` line is also removed from v1. I don't know what it meant, I've never used Mojo.

**Comment by soraros** [comment]
@jabbalaci Good catch. Fixed.

**Comment by martinvuyk** [comment]
In my machine it seems like the `InlineArray` is a bit faster than SIMD, but this will likely change with server grade CPUs

Doing a global var cache and passing it as a function argument to `is_muchausen()`:
```text
"InlineArray[uint32]",3449.9183376666665,3
"SIMD[uint32]",3860.0218596666668,3
```
Doing a local alias cache inside the function `is_muchausen()`
```text
"InlineArray[uint32]",3235.4407679999999,3
"SIMD[uint32]",3797.3388070000001,3
```

See PR #68 for more benchmark results in my machine

**Comment by soraros** [comment]
Closing due to lack of interest.

**Pull request closed without merging**
