### PR TITLE
add scheme implementation

### PR DESCRIPTION
**Pull request by uninhm**

### CODE REVIEW

**Comment by uninhm** [comment]
@jabbalaci I don't use Manjaro, but there is [a package](https://aur.archlinux.org/packages/chez-scheme) in the AUR you can install

**Comment by jabbalaci** [comment]
Thanks, got it.

**Comment by jabbalaci** [comment]
`stalin` requires GCC6, but it fails to compile on my system:
```
make: *** [Makefile:917: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
 -> error making: gcc6 (gcc6-libs gcc6)
```

**Comment by jabbalaci** [comment]
`gsc` is something else on my system:
```
$ gsc
GPL Ghostscript 9.56.1 (2022-04-04)
Copyright (C) 2022 Artifex Software, Inc.  All rights reserved.
...
```

**Comment by jabbalaci** [comment]
It was added. Thanks for the contribution.

I had to put gsc and stalin to comment.

**Comment by uninhm** [comment]
@jabbalaci that's a shame, they were the fastest

**Comment by uninhm** [comment]
@jabbalaci Gambit is [officially available for Manjaro](https://software.manjaro.org/package/gambit-c) and for Stalin I had to use the [Debian's prebuilt binaries](https://packages.debian.org/bullseye/stalin) because I couldn't build it either

**Comment by jabbalaci** [comment]
I could install gambit.

`make build1` works. However, `make build2` builds an exe that is executable but doesn't produce any output:

```
$ make build1
gambitc -:debug=pqQ0 -exe -cc-options '-O3' main.scm
$ ./main
0
1
3435
438579088

$ make build2
gambitc -:debug=pqQ0 -exe -cc clang -cc-options '-O3' main.scm
$ ./main
$
```

**Comment by jabbalaci** [comment]
stalin drops an error:

```
$ make build3
stalin -s -On -Ot -Ob -Om -Or -dC -dH -dP\
        -copt '-O3' main.scm
Unknown architecture: unknown
make: *** [Makefile:14: build3] Error 255
```

stalin has a script `stalin-architecture-name` which doesn't recognise my architecture:

```
$ ./stalin-architecture-name 
unknown
```

`uname -m`/`uname -s` produces "x86_64/Linux" on my system, but this case is not handled in `stalin-architecture-name`.

**Comment by uninhm** [comment]
@jabbalaci specify your architecture with `-architecture`

**Comment by jabbalaci** [comment]
Any idea what could be wrong with `make build2` ?

```
$ gambitc -:debug=pqQ0 -exe -cc clang -cc-options '-O3' main.scm
$ ./main                     
$ echo $?    
71
```

The produced EXE exits with an error code and doesn't print anything on the screen.

clang is installed:

```
$ clang --version
clang version 14.0.6
Target: x86_64-pc-linux-gnu
Thread model: posix
```

**Comment by uninhm** [comment]
@jabbalaci I don't know why it doesn't work with clang, maybe we have to pass some flags to clang for it to not break anything? Did you try without optimization? Does it work?

**Comment by jabbalaci** [comment]
```
$ gambitc -cc clang main.scm
/bin/ld: /bin/../lib64/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../lib64/Scrt1.o: in function `_start':
/build/glibc/src/glibc/csu/../sysdeps/x86_64/start.S:103: undefined reference to `main'
clang-14: error: linker command failed with exit code 1 (use -v to see invocation)
*** ERROR IN ##main -- target compilation or link failed while compiling "main.scm"
```

**Comment by uninhm** [comment]
@jabbalaci the `-exe` flag is mandatory

**Comment by jabbalaci** [comment]
> the `-exe` flag is mandatory

In that case there's absolutely no output, just a broken EXE.

**Comment by jabbalaci** [comment]
How can you get the version information of `stalin`? None of these works: -h, --help, -version, --version, -V, etc.

**Comment by uninhm** [comment]
The version is 0.11, released 15 years ago

**Comment by jabbalaci** [comment]
The tests were re-run. Please check.

**Comment by uninhm** [comment]
Are you taking compile time as if it were part of the runtime?

**Comment by jabbalaci** [comment]
No. Runtime is without compile time.

**Pull request merged**
