### PR TITLE
Mojo version added

### PR DESCRIPTION
**Pull request by dorjeduck**
Here a Mojo version for the SpeedTests 

How to compile/run:

1.) Install magic: https://docs.modular.com/magic/
2.) Compile (This will install Mojo when run first time):
    magic run mojo build -o main main.mojo  
3.) Run: 
    ./main

### CODE REVIEW

**Comment by jabbalaci** [comment]
How can I get the mojo version from anywhere? `magic run mojo --version` works in the project directory, but outside of it I get an error:

```
$ magic run mojo --version
  × could not find pixi.toml, pyproject.toml, or mojoproject.toml which is configured to use magic
```

In my automation script (inside `_automation/`) I need to get the version info.

**Comment by dorjeduck** [comment]
When you run 

```
magic run which mojo
```

in the project directory you should get the absolute path to the Mojo binary of this project. 

With this absolute path, you should get the version globally, eg:
```
/Users/dorjeduck/dev/2024/maxgrad/.magic/envs/default/bin/mojo --version
```
works here. 

Alternatively you can also run 
```
magic shell
```
in the project directory and then ```which mojo```

Please let me know if this works for you or if we should find another solution.

**Comment by jabbalaci** [comment]
Thanks, the `magic run which mojo` trick works. I'll integrate this part a bit later.

**Comment by dorjeduck** [comment]
Thanks a lot for this project, very interesting to see the comparison.

**Comment by jabbalaci** [comment]
Thanks, it was integrated.

I've never used Mojo. Could you say a few words about it? Is it worth diving into it?

**Comment by dorjeduck** [comment]
Mojo is basically Python on steroids. 😉

It's a young language, so there are still breaking changes as it matures. One goal for Mojo is to become a superset of Python within the next two years, offering the performance boosts you're seeing in speed tests. But you'll also be able to write GPU kernels with it—making Mojo a one-stop language for all your needs.

Right now, the developer team is focused on GPU support, which should come in the next release. Other features, like for example dynamic polymorphism and classes, are still on the roadmap. In short, Mojo is super promising, especially with Chris Lattner leading the way, but it's not quite production-ready yet.

**Comment by jabbalaci** [comment]
Thanks for the info. It's an interesting project indeed.

**Comment by dorjeduck** [comment]
You're very welcome!

Just a small note: I noticed that the "see source" link for Mojo is missing in the README.md... 😉

**Comment by jabbalaci** [comment]
Right. "see source" was added.

**Comment by dorjeduck** [comment]
I've noticed an issue in the ```get_cache``` method I implemented, sorry for that. While it seems to work here, it's actually unsafe and should not be done like that. The correct implementation of the get_cache method should be:

```
fn get_cache() -> List[Int]:
    var ca = List[Int](capacity=10)
    ca.append(0)
    for i in range(1, 10):
        ca.append(i**i)
    return ca
 ```
 
The list initialization doesn't guarantee that the space is allocated properly, adding elements through ```append``` takes care of that.

Would you like me to open another PR to fix this, or can you make the change directly?

**Comment by jabbalaci** [comment]
Could you send a PR? And after that I'll re-run the test.

**Comment by jabbalaci** [comment]
I got some comments on Mojo, please see https://github.com/jabbalaci/SpeedTests/pull/63

**Comment by dorjeduck** [comment]
thanks, i posted my comment to it :-D These two are far more Mojo experts than I am, so basically the ones to listen to ...

**Pull request merged**
