### PR TITLE
Add V lang

### PR DESCRIPTION
**Pull request by unihernandez22**
~5 seconds

### CODE REVIEW

**Comment by jabbalaci** [comment]
What is V lang? Never heard of it. How to install it on Linux? Where is the lang.'s homepage?

**Comment by unihernandez22** [comment]
https://vlang.io

**Comment by jabbalaci** [comment]
@unihernandez22 You are not a chatterbox, are you?

**Comment by unihernandez22** [comment]
No hahahaha

**Comment by jabbalaci** [comment]
LOL

**Comment by jabbalaci** [comment]
Thanks, it was added. It's a very interesting language, I'll look into it.

**Pull request merged**
