### PR TITLE
haskell

### PR DESCRIPTION
**Pull request by uninhm**

### CODE REVIEW

**Comment by uninhm** [comment]
The algorithm is basically the same but recursive.

**Comment by jabbalaci** [comment]
I get an error:

```
$ make
ghc -O2 main.hs
[1 of 1] Compiling Main             ( main.hs, main.o )

main.hs:1:1: error:
    Could not find module ‘Prelude’
    There are files missing in the ‘base-4.14.1.0’ package,
    try running 'ghc-pkg check'.
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
  |
1 | isMunchausen :: Int -> Int -> Int -> [Int] -> Bool
  | ^
make: *** [Makefile:2: compile] Error 1
```

I don't know Haskell so I need help here.

**Comment by jabbalaci** [comment]
Thanks for the contribution.

**Comment by jabbalaci** [comment]
@uninhm : I need some help. I cannot compile v2 on my new machine. I have Manjaro Linux installed.

```
$ make v2
cabal: Could not resolve dependencies:
[__0] trying: haskell-0.1.0.0 (user goal)
[__1] next goal: base (dependency of haskell)
[__1] rejecting: base-4.15.1.0/installed-4.15.1.0 (constraint from project
config TODO requires ==4.14.3.0)
[__1] fail (backjumping, conflict set: base, haskell)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, haskell

# optimized, see v2 in Makefile
cp main_v2.hs main.hs
ghcup set ghc 8.10.7
[ Error ] The version 8.10.7 of the tool ghc is not installed.
make: *** [Makefile:13: v2] Error 5

$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.0.2
```

Installed packages:

```
community/ghc-static 9.0.2-1 (163.5 MiB 1.9 GiB) (Installed)
    The Glasgow Haskell Compiler - Static Libraries and Documentation
community/ghc-libs 9.0.2-1 (19.1 MiB 138.8 MiB) (Installed)
    The Glasgow Haskell Compiler - Dynamic Libraries
community/ghc 9.0.2-1 (32.1 MiB 192.6 MiB) (Installed)
    The Glasgow Haskell Compiler
community/cabal-install 3.4.0.0-165 (1.6 MiB 10.7 MiB) (Installed)
    The command-line interface for Cabal and Hackage.
```

**Comment by uninhm** [comment]
`ghcup set ghc 8.10.7`

That command is failing, do you have `ghcup` installed?

**Comment by jabbalaci** [comment]
My GHC version was 9.0.2 before changing to 8.10.7 . Could we update the Makefile for a newer GHC version?

**Comment by uninhm** [comment]
@jabbalaci I'm not sure because I didn't write that version, but give it a try and, if it works, you can update it :P

**Pull request merged**
