### PR TITLE
Use uint32 for Nim (as in Rust)

### PR DESCRIPTION
**Pull request by Yardanico**
C version uses a 32-bit int too (although signed), maybe need to change it as well?

### CODE REVIEW

**Comment by jabbalaci** [comment]
Thank you. I tried both versions, they gave the same results. So I would leave the original integer types.

**Comment by jabbalaci** [comment]
I changed Rust's u32's to i32's, there is no difference in the runtime speed.

**Comment by Yardanico** [comment]
> I changed Rust's u32's to i32's, there is no difference in the runtime speed.

Now change it to int64 and change C to use int64_t so the benchmarks are actually fair.

**Comment by jabbalaci** [comment]
With Nim I made an int32 and an int64 version. Same speed.

**Comment by Yardanico** [comment]
@jabbalaci then I don't see the point of the benchmark - usually it's to compare roughly SAME implementations in different languages (with same int sizes, etc)

**Comment by jabbalaci** [comment]
They are roughly the same, yes.

**Comment by unihernandez22** [comment]
I'm in agreement with @Yardanico, it should be the same for all languages.

**Comment by jabbalaci** [comment]
I'm in agreement with my previous comment: "Make your own tests with 32 and 64 bit integers. If you find a difference, let me know."

**Pull request closed without merging**
